[package]
name = "sml"
version = "0.1.0"
authors = ["Stoozy <mahinsemail@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
curl = "0.4.35"
serde_json = "1.0"
hyper = "0.13.8"
ureq = "2.0.2"
